apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: nivoxai
spec:
  template:
    spec:
      containers:
        - name: backend-api
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/nivoxai-backend-api:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: nivoxai-config
                  key: DATABASE_URL
