apiVersion: v1
kind: ConfigMap
metadata:
  name: nivoxai-config
  namespace: nivoxai-dev
data:
  AI_BASE_URL: "http://backend-ai:8000"
  AI_SERVICE_URL: "http://backend-ai:8000"
  NEXT_PUBLIC_API_BASE_URL: "http://backend-api:4000"
  NEXT_PUBLIC_ANALYTICS_URL: "http://backend-ai:8000"
  DATABASE_URL: "postgresql://postgres:REPLACE_ME@rds-endpoint-placeholder.amazonaws.com:5432/nivoxai"
  PGHOST: "rds-endpoint-placeholder.amazonaws.com"
  PGPORT: "5432"
  PGDATABASE: "nivoxai"
  PGUSER: "postgres"
  POSTGRES_DB: "nivoxai"
  POSTGRES_USER: "postgres"
  PORT: "4000"
