apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nivoxai-dev

resources:
  - ../../base/core
  - ./namespace.yaml
  - ./configmap.yaml
  - ./secret.template.yaml

images:
  - name: nivoxai-backend-ai
    newName: <ECR_REGISTRY>/nivoxai-backend-ai
    newTag: latest
  - name: nivoxai-backend-api
    newName: <ECR_REGISTRY>/nivoxai-backend-api
    newTag: latest
  - name: nivoxai-frontend
    newName: <ECR_REGISTRY>/nivoxai-frontend
    newTag: latest
